Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	articles_indexs
	1

[Sat Mar 21 22:31:49 2020]
rule articles_indexs:
    input: dataset/CaL/article/fphys-07-00481.pdf
    output: dataset/CaL/articles_indexs/fphys-07-00481.txt
    jobid: 0
    wildcards: channel=CaL, article=fphys-07-00481

[Sat Mar 21 22:31:49 2020]
Error in rule articles_indexs:
    jobid: 0
    output: dataset/CaL/articles_indexs/fphys-07-00481.txt

RuleException:
URLError in line 19 of /home/mark/Рабочий стол/bioinf/urfu_bioinf_2020/Snakefile:
<urlopen error [Errno 2] No such file or directory: '/home/mark/Рабочий стол/bioinf/urfu_bioinf_2020/articles_indexs.ipynb'>
  File "/home/mark/Рабочий стол/bioinf/urfu_bioinf_2020/Snakefile", line 19, in __rule_articles_indexs
  File "/home/mark/anaconda3/lib/python3.7/urllib/request.py", line 222, in urlopen
  File "/home/mark/anaconda3/lib/python3.7/urllib/request.py", line 525, in open
  File "/home/mark/anaconda3/lib/python3.7/urllib/request.py", line 543, in _open
  File "/home/mark/anaconda3/lib/python3.7/urllib/request.py", line 503, in _call_chain
  File "/home/mark/anaconda3/lib/python3.7/urllib/request.py", line 1451, in file_open
  File "/home/mark/anaconda3/lib/python3.7/urllib/request.py", line 1490, in open_local_file
  File "/home/mark/anaconda3/lib/python3.7/concurrent/futures/thread.py", line 57, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/mark/Рабочий стол/bioinf/urfu_bioinf_2020/.snakemake/log/2020-03-21T223149.361703.snakemake.log
