Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	articles_indexs
	1	cat_indexs
	1	fusion
	3

[Tue Mar 24 18:23:09 2020]
rule articles_indexs:
    input: dataset/CaL/article/fphys-07-00481.pdf
    output: dataset/CaL/articles_indexs/fphys-07-00481.txt
    jobid: 2
    wildcards: channel=CaL, article=fphys-07-00481

[Tue Mar 24 18:23:11 2020]
Finished job 2.
1 of 3 steps (33%) done

[Tue Mar 24 18:23:11 2020]
rule cat_indexs:
    input: dataset/CaL/articles_indexs/fphys-07-00481.txt
    output: indexs.txt
    jobid: 1

Removing temporary output file dataset/CaL/articles_indexs/fphys-07-00481.txt.
[Tue Mar 24 18:23:11 2020]
Finished job 1.
2 of 3 steps (67%) done

[Tue Mar 24 18:23:11 2020]
rule fusion:
    input: indexs.txt, fixed.txt
    output: workflow/clear_indexs.csv
    jobid: 0

[Tue Mar 24 18:23:13 2020]
Error in rule fusion:
    jobid: 0
    output: workflow/clear_indexs.csv

RuleException:
CalledProcessError in line 16 of /home/mark/Рабочий стол/bioinf/urfu_bioinf_2020/Snakefile:
Command 'set -euo pipefail;  jupyter-nbconvert --execute  --to notebook --ExecutePreprocessor.timeout=-1 '/home/mark/Рабочий стол/bioinf/urfu_bioinf_2020/.snakemake/scripts/tmp07jcd7vu.fusion.ipynb'' returned non-zero exit status 1.
  File "/home/mark/Рабочий стол/bioinf/urfu_bioinf_2020/Snakefile", line 16, in __rule_fusion
  File "/home/mark/anaconda3/lib/python3.7/concurrent/futures/thread.py", line 57, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/mark/Рабочий стол/bioinf/urfu_bioinf_2020/.snakemake/log/2020-03-24T182309.023654.snakemake.log
